// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

console.log('Loading Stimulus controllers index...');
import { application } from "./application"

import CesiumController from "./cesium_controller"
application.register("cesium", CesiumController)

import CesiumImpactController from "./cesium_impact_controller"
application.register("cesium-impact", CesiumImpactController)

import EarthController from "./earth_controller"
application.register("earth", EarthController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImpactController from "./impact_controller"
application.register("impact", ImpactController)

import NeoBrowserController from "./neo_browser_controller"
application.register("neo-browser", NeoBrowserController)

import NeoSelectorController from "./neo_selector_controller"
application.register("neo-selector", NeoSelectorController)

console.log('All Stimulus controllers registered. Available controllers:', application.controllersByName);
