development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis, :production, :url) || ENV["REDIS_URL"] || "redis://localhost:6379/0" %>
  channel_prefix: impactor_2025_production
